### ISSUE TITLE
Doubt 

### ISSUE THREAD

**Issue by SergioGomera** [fsaris/EspHome-AwoX-BLE-mesh-hub#1]
Is not a really issue, but how can I install or use this integration?? I need an esp32?? I can install in home assistant thx in advance for your great job.

**Comment by fsaris** [comment]
Yes, you will need a esp32 and you can use the ESPHome addon in HomeAssistent to install this using the yaml config from https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/blob/main/awox-ble-mesh-hub.yaml
Further you need to have a MQTT broker running/configured in HomeAssistent.

Will update the README later today to list these requiremens

**Comment by fsaris** [comment]
updated readme
