### ISSUE TITLE
Will this component work with a Raspberry Pi Pico W?

### ISSUE THREAD

**Issue by danieldur** [fsaris/EspHome-AwoX-BLE-mesh-hub#10]
Hello Frans,

I recently tried to run this component on a Raspberry Pi Pico W and I couldn't (can't provide the logs at the moment). I am guessing it is not working on the Pico. It's this correct?

Alternatively, do you have any ESP recommended board? Would a D1 mini work (https://www.berrybase.de/en/d1-mini-esp8266-entwicklungsboard?c=2473)?

Thank you!

**Comment by fsaris** [comment]
You need a ESP32 module like ESP32 Wroom 
https://a.aliexpress.com/_EugpvJz

The d1 and pico are different type of boards
