### ISSUE TITLE
Duplicated Product_ID Mqtt

### ISSUE THREAD

**Issue by SergioGomera** [fsaris/EspHome-AwoX-BLE-mesh-hub#117]
Hello, first of all, thx for this increíble work.
After a few minimum problems to install and used it, I discovered 2 of my Eglo Spot are discovered in Mqtt with the same product_id, but there are a different Mqtt device, I can control each one separately but, when I try to add the device config into the yaml in esphome, I can only add 1 item by product id, and result duplicated name and icon in 2 differents devices.
![Captura de pantalla 2024-12-23 a las 9 13 44](https://github.com/user-attachments/assets/f80d6a2f-1b59-4819-b111-9c17d44e350d)
![Captura de pantalla 2024-12-23 a las 9 14 26](https://github.com/user-attachments/assets/0989e600-9ae3-4d91-8647-ea9d0a8aaeb8)

![IMG_1142](https://github.com/user-attachments/assets/d48bdd21-d7bf-4e58-8ad4-08f9826f3d01)

There is any solution to this?? how I can add this device info with same product_id??

**Comment by fsaris** [comment]
The product id is not unique for each device but represent the product type so to say.

So if you have 2 equal devices you only need to configure the product id once
