### ISSUE TITLE
Light panel changes colour by itself after a while

### ISSUE THREAD

**Issue by Marcel1202** [fsaris/EspHome-AwoX-BLE-mesh-hub#22]
Whenever I turn off my light panel electrically and turn it back on, it is always red at first (which is fine, I guess).
I can change the colour just fine using HA with your component, but after a few minutes the light changes colour by itself.
The changes don't seem arbitrary, each colour is displayed for a few seconds, and it cycles in patterns.

I haven't connected the panel to an Awox account because I don't know how to find out the mesh password there.
Is this some kind of demo mode? How can I find out mesh name and password when it is not the default after factory reset?

**Comment by Marcel1202** [comment]
Fixed this by adding code into your Awox Integration that logs mesh name and password. Still, an easier way to do this and better instructions would be appreciated. Anyway, thanks for providing this component.

**Comment by fsaris** [comment]
It's on my list to add pairing of a new light to feature set. But that more of a winter project 😉
