### ISSUE TITLE
Bug: MQTT entity name starts with the device name in your config - HA 2023.8

### ISSUE THREAD

**Issue by Dillton** [fsaris/EspHome-AwoX-BLE-mesh-hub#24]
Hello @fsaris.
I just want to notify you about breaking change in HA 2023.8.0.

From here https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

Discovered entities with a name that starts with the device name.

This stops working in version 2024.2.0. Please address before upgrading.

In screenshot I marked the AwoX entities to confirm this change:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/68992112/c528be6c-10a4-4079-b683-b75862fd9fb3)

**Comment by fsaris** [comment]
TNX for the message, will update the code next week to apply to the new rules

**Comment by fsaris** [comment]
resolved in current main version
