### ISSUE TITLE
Login without old integration

### ISSUE THREAD

**Issue by NeonPimpZ** [fsaris/EspHome-AwoX-BLE-mesh-hub#27]
How do we get the `mesh_name` and `mesh_password` if we cant use your old HA integration?
I migrated to the newer AwoX HomeControl App some time ago and cant login to the old integration anymore.

The ESPHome component finds my light but can't connect to it, as the name & pw are wrong.

**Comment by gallaid** [comment]
Just reset your password on the Awox app.

**Comment by fsaris** [comment]
I created a jsfiddle you can use to get the credentials from you awox account. see readme or https://jsfiddle.net/franssaris/uncm54vb/36/
