### ISSUE TITLE
QUESTION: Eglo spot 170

### ISSUE THREAD

**Issue by Dillton** [fsaris/EspHome-AwoX-BLE-mesh-hub#30]
Hello @fsaris.

I have a question regarding my ES170 lights.
I am using 8 of these lights and 5 of them disconnects and reconnects every few seconds/minutes and sometimes stays connected for few hours/days.
I have also EGLO PLUG  PLUS which also stays connected without any problem.

Did you or anyone else observed similar behaviour? I think the type of device might not matter.
This is history of the lights in HA:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/68992112/2a41a180-1f04-4bcc-bd26-11b988f13a08)

Do you have maybe any idea what I can try to do to eliminate this?
It's starting to be really annoying when you need to turn on/off the light and must wait until it become available.

**Comment by fsaris** [comment]
Looks similar to #12
