### ISSUE TITLE
[BUG] EGLO PLUG PLUS in unknown state

### ISSUE THREAD

**Issue by Dillton** [fsaris/EspHome-AwoX-BLE-mesh-hub#52]
Hello @fsaris 

There is a minor bug I would say but I don't know if only with eglo plug or in gerenal with switch entities.
Anyway sometimes when HA or MQTT add-on restarts, mainly because of some update, my eglo plug is then in unknown state.
However when I call turn on/off service from HA the plug is correctly turned on/off and the state is then reported correctly.
This is never happened with lights.

Unfortunatelly I don't have any logs collected so far.
I will try to collect them but it's not happening with every restart so it might be tricky.

![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/68992112/28c540ca-4e11-4139-9e6f-020569cefb11)

**Comment by fsaris** [comment]
ah, see that the status messages for plug aren't retained. So it waits for a new update of the device.

This is fixed in the dev branch
