### ISSUE TITLE
[Feature request] Color transition

### ISSUE THREAD

**Issue by oxigen-dev** [fsaris/EspHome-AwoX-BLE-mesh-hub#57]
Hi @fsaris ,

Would it be possible to add the Color transition mode as an effect to the device in HA? 
I think it should be this: https://github.com/oxigen-dev/python-awox-mesh-light/blob/491bf8414f493ee6b1221dec20d03c0984bc0048/awoxmeshlight/__init__.py#L272

The lamps also have some candle flicker mode.. For me it is not a must, I was mentioning is just for completeness :)

Thanks!

**Comment by fsaris** [comment]
@oxigen-dev in the dev branch there is now support for 2 effects: 

- candle (starts a flickering effect)
- color loop (transitions through a color pallet)

**Comment by oxigen-dev** [comment]
Thanks, I'll test them!

**Comment by oxigen-dev** [comment]
@fsaris I was doing some tests. Color loop seems to be working fine.
The candle effect is most of the time not starting. I was randomly pressing everything for 1 minute then it started working.
If an effect is activated and eg. I'm manually activating a Scene then the effect stays on "color loop" and doesn't go back automatically to "stop".

**Comment by fsaris** [comment]
> If an effect is activated and eg. I'm manually activating a Scene then the effect stays on "color loop" and doesn't go back automatically to "stop".

That seems to be an issue with HA. Had that too but the reported state was updated by the esp.
Will do some extra testing but for now it looks to be a HA frontend issue.

> The candle effect is most of the time not starting. I was randomly pressing everything for 1 minute then it started working

Probably related to the issue above. Did you check the mqtt Transmitted messages for that light? Was the `effect` value correctly send?

**Comment by oxigen-dev** [comment]
Starting with the effect `stop`. After selecting `candle`, nothing happens:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/f9bfb8f8-5f48-4a15-b302-01194a4c4056)
If selecting `color_loop`:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/0b7cddce-c42c-4488-ace3-49299ac31110)
If selecting `candle` after `color_loop`:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/bd9875f4-15b6-4a9d-b427-03f1c0cf4be2)

It is there for only a msec :)

**Comment by fsaris** [comment]
These are the state messages, but I'm interested in the command messages.

These can be viewed in HA.

Click on `MQTT INFO` on the device page 
![Screenshot_2024-01-28-11-07-06-74_c3a231c25ed346e59462e84656a70e50](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/4019341/439d289b-9b33-4a28-8cc3-7d6ab0846de6)

And look for `Transmitted messages`

**Comment by oxigen-dev** [comment]
1. Effect selected: `stop`
2. Activate scene (100% brightness, white) -> effect in HA changed to `candle`. Maybe `stop` or `off` (as I've seen in other integrations) should be the first in the list.
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/dace2de0-5bc5-4c29-8531-73916b3c1fed)
3. Effect: `color_loop`
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/66def8e1-32f3-4b9b-87c8-fdf52fc4531d)
4. Effect: `candle`
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/1d1429b9-9122-44f2-97a4-f252422a5a39)
5. Effect: `stop`
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/6086b46a-36da-442e-b3fa-a1bdac1a4318)
6. Effect: `candle` -> nothing happens
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/66b3df95-8ea3-49bc-8872-17796cd4204e)

**Comment by fsaris** [comment]
So after `stop` it brakes?

When `effect: stop` is send as command it's not part of the `status` response. Maybe that's needed. Not sure how other integrations do this.
I see that Zigbee2mqtt doesn't add the `effect` to the `state` response.


> Maybe stop or off (as I've seen in other integrations) should be the first in the list.

I only found examples where it's the last in the list (Zigbee2mqtt, Tasmota).

**Comment by oxigen-dev** [comment]
> So after `stop` it brakes?

Just stop->candle is not working.

> 
> When `effect: stop` is send as command it's not part of the `status` response. Maybe that's needed. Not sure how other integrations do this. I see that Zigbee2mqtt doesn't add the `effect` to the `state` response.
> 
> > Maybe stop or off (as I've seen in other integrations) should be the first in the list.
> 
> I only found examples where it's the last in the list (Zigbee2mqtt, Tasmota).

This is a Philips Hue bulb with Zigbee2MQTT:
1. Effect was set to `blink`
2. Effect was set to `stop_effect`
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/0433248f-8396-41de-ab20-b99a889f3490)

List of effects (I think it follows the same logic as you):
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/f8ce7ac5-1004-42f3-9d33-25d20f1a54a0)

State topic doesn't contain any information about the selected effect:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/fefc69b9-85c7-4790-8e6c-f1614b67fcf4)
