### ISSUE TITLE
[Feature request] Time duration of transitions between color and effects

### ISSUE THREAD

**Issue by oxigen-dev** [fsaris/EspHome-AwoX-BLE-mesh-hub#60]
Hi @fsaris ,

I was just wondering whether it would be possible to add the time transition functionality.
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/124933927/ed7ba76f-845b-49fb-8eba-ef9d4c3c96d7)

Now it doesn't take into consideration the time set.

Thanks!

**Comment by fsaris** [comment]
The lights don't support this feature. You can set `fade_duration` and a `color_duration` value but that's only for `sequence` (the `color loop` effect.

**Comment by oxigen-dev** [comment]
@fsaris What if that would be implemented on ESP side? Eg. Brightness is now 0%, I'd like to set it to 100% in 1000 ms and it would then increase the brightness with +10% in every 100 ms?

**Comment by fsaris** [comment]
As this is a hub and not a real light controller I don't think that will work properly. 

To much to consider:
- lag of the mesh network
- other commands comming in during transition for same device 
- handling transition intervals and also handling other lights
