### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Kees48** [fsaris/EspHome-AwoX-BLE-mesh-hub#64]
During installation I got this ERRORS:

INFO Successfully compiled program.
INFO Resolving IP address of awox-ble-mesh-hub.local
ERROR Error resolving IP address of awox-ble-mesh-hub.local. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -5] No address associated with hostname.

AwoX BLE mesh hub is off line
LOG:
INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/awox-ble-mesh-hub.yaml...
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Starting log output from awox-ble-mesh-hub/debug
INFO Connected to MQTT broker!

**Comment by fsaris** [comment]
These look like general esphome setup errors. Connect using a wired connection and check the logs
