### ISSUE TITLE
Size to big?

### ISSUE THREAD

**Issue by OkOtChA666** [fsaris/EspHome-AwoX-BLE-mesh-hub#65]
So, I've followed your sugestion and i've bought an ESP board
When following instruction at the end, this appears

![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/92456100/04bd5d26-8232-4ebd-aa7c-0ec6094f721d)

![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/92456100/8005254b-0d2b-49a6-a17c-585daa1d82bb)

I'm confused about the file size limit

Any idea?

**Comment by fsaris** [comment]
See #63 switch framework to esp-idf or if not possible use a wired (USB) connection to flash 

```
framework:
    # Be sure to "Clean Build Files" when switching framework
    type: esp-idf
```
