### ISSUE TITLE
Program size too big

### ISSUE THREAD

**Issue by JbbDE** [fsaris/EspHome-AwoX-BLE-mesh-hub#69]
[logs_awox-adapter_run.txt](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/files/14322971/logs_awox-adapter_run.txt)
with the new update the program size is too big for my ESP32, did I do something wrong?

**Comment by fsaris** [comment]
See https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/issues/63 switch framework to esp-idf or if not possible use a wired (USB) connection to flash

```
framework:
    # Be sure to "Clean Build Files" when switching framework
    type: esp-idf
```
