### ISSUE TITLE
NO devices discovered

### ISSUE THREAD

**Issue by Jinguba** [fsaris/EspHome-AwoX-BLE-mesh-hub#73]
I've tried ti configure my awox devices and followed documentation.

I noticed that on the build I see some warnings

Also I believe the connection to MQTT Broker is working, as per the logs:
![image](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/assets/69633498/f0f414e7-cf16-4bfa-baf4-443eeaa0a4f4)

THis is my configuration:

esphome:
  name: esphome-web-719788
  friendly_name: Awox

esp32:
  board: esp32dev
  framework:
    type: esp-idf

ota:

logger:

mqtt:
  broker: core-mosquitto
  username: username
  password: password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub

esp32_ble_tracker:
  scan_parameters:
    active: false

awox_mesh:
  mesh_name: meshname
  mesh_password: meshpassword
  device_info:
    # Example device type, see device info in HomeAssistant or MQTT message to find the 'product_id'
    - product_id: 0x26
      device_type: RGB
      manufacturer: EGLO
      name: EGLOPanel 60X60
      model: EPanel_600

Can you please help? What am I doing wrong?

**Comment by fsaris** [comment]
See #66 for more guidance
