### ISSUE TITLE
update impossibe : platform key is required

### ISSUE THREAD

**Issue by alka79** [fsaris/EspHome-AwoX-BLE-mesh-hub#95]
Hi,
I tried to update and could not, with a red message about a missing platform key. 

Along the versions of ESPHome, there was this breaking change
https://github.com/esphome/esphome/pull/6459

now `- platform: esphome` is required for ota update.

Maybe update the yaml example config to reflect this.
Not a big deal.
Thanks

**Comment by fsaris** [comment]
done
